version: '3.3'
services:
  react-front:
    container_name: react-front
    image: react-front-image
    volumes:
      - '.:/srv/chn_react-front-master'
      - '/srv/chn_react-front-master/node_modules'
    ports:
      - 80:3000
    restart: "always"
    networks:
      app_net:
        ipv4_address: 172.16.238.10

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
